import { ActionCharacter, ActionCharacterDrawState } from '../models/ActionCharacter'
import { CharacterType, FieldPlayer } from './context'
import { SkillType } from '@/models/Skill'

export const testPlayerData: ActionCharacter[] = [
  {
    name: 'フェリス',
    type: 'FieldPlayer',
    drawState: ActionCharacterDrawState.Normal,
    status: {
      currentHitPoint: 865,
      currentSpecialPoint: 500,
      condition: '通常',
      command: undefined,
      onEffect: undefined,
      onEffectPoint: 0,
    },
    parameter: {
      attack: 80,
      defense: 100,
      hitPoint: 865,
      specialPoint: 500,
      speed: 50,
      level: 0,
      specialAttack: 0,
      specialDefense: 0,
      experiencePoint: 0,
    },
    skills: [
      {
        name: '並列処理',
        type: SkillType.PhysicalAllAttack,
        power: 450,
        specialPointConsumption: 100,
        description: '敵全体にダメージ',
      },
      {
        name: 'スピンロック',
        type: SkillType.SpecialAllAttack,
        power: 450,
        specialPointConsumption: 150,
        description: '敵１体に大ダメージ',
      },
    ],
    commandOptions: [],
  },

  {
    name: 'ゴーファー',
    type: 'FieldPlayer',
    drawState: ActionCharacterDrawState.Normal,
    status: {
      currentHitPoint: 512,
      currentSpecialPoint: 300,
      condition: '通常',
      command: undefined,
      onEffect: undefined,
      onEffectPoint: 0,
    },
    parameter: {
      attack: 20,
      defense: 100,
      hitPoint: 512,
      specialPoint: 300,
      speed: 60,
      level: 0,
      specialAttack: 0,
      specialDefense: 0,
      experiencePoint: 0,
    },
    skills: [
      {
        name: 'ゴルーチン',
        type: SkillType.PhysicalAllAttack,
        power: 450,
        specialPointConsumption: 100,
        description: '敵全体にダメージ',
      },
      {
        name: 'ガベージコレクション',
        type: SkillType.PhysicalAttack,
        power: 450,
        specialPointConsumption: 100,
        description: '敵１体に大ダメージ',
      },
    ],
    commandOptions: [],
  },
  {
    name: 'タックス',
    type: 'FieldPlayer',
    drawState: ActionCharacterDrawState.Normal,
    status: {
      currentHitPoint: 640,
      currentSpecialPoint: 300,
      condition: '通常',
      command: undefined,
      onEffect: undefined,
      onEffectPoint: 0,
    },
    parameter: {
      attack: 30,
      defense: 100,
      hitPoint: 640,
      specialPoint: 300,
      speed: 70,
      level: 0,
      specialAttack: 0,
      specialDefense: 0,
      experiencePoint: 0,
    },
    skills: [
      {
        name: 'seccomp',
        type: SkillType.PhysicalAttack,
        power: 450,
        specialPointConsumption: 100,
        description: '特定の',
      },
    ],
    commandOptions: [],
  },
  {
    name: 'ドロイド',
    type: 'FieldPlayer',
    drawState: ActionCharacterDrawState.Normal,
    status: {
      currentHitPoint: 720,
      currentSpecialPoint: 300,
      condition: '通常',
      command: undefined,
      onEffect: undefined,
      onEffectPoint: 0,
    },
    parameter: {
      attack: 50,
      defense: 100,
      hitPoint: 720,
      specialPoint: 300,
      speed: 90,
      level: 0,
      specialAttack: 0,
      specialDefense: 0,
      experiencePoint: 0,
    },
    skills: [
      {
        name: 'ガベージコレクション',
        type: SkillType.PhysicalAttack,
        power: 450,
        specialPointConsumption: 100,
        description: '相手の時間を止める',
      },
    ],
    commandOptions: [],
  },
]
